### ISSUE TITLE
Remove UNet Model Implementation of Lightning Bolts

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/pytorch-caney#62]
Lightning bolts has not been updated and has breaking changes with the latest pytorch lightning.

https://github.com/Lightning-Universe/[lightning-bolts](https://github.com/Lightning-Universe/lightning-bolts)

We should remove any code base using it 

ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/__init__.py)

**Comment by cssprad1** [comment]
Consider fixed with #63
